### PR TITLE
Added `o3.experimental.FullTensorProductv2` + benchmaking and plotting nitpicks

### PR DESCRIPTION
**Pull request by mitkotak**
- Added `o3.experimental.FullTensorProductv2` to the suite of benchmarks.
    - Curious to see how it performs on your machine. 
    - Also if possible could you try out with [this ](https://intel.github.io/intel-extension-for-pytorch/cpu/2.3.100+cpu/tutorials/features.html)extension
- Keeping warmup to 10 steps just to be safe :)
- Sorry could not read the colors before. I am colorblind :(

### CODE REVIEW

**Comment by teddykoker** [comment]
Re-ran benchmarks:

benchmark

A few notes:

 * surprisingly, torch v2 seems to do marginally worse than plain torch, though we are measuring single-thread CPU performance so that could be a caveat.
 * the addition of `ipex` seems to make no significant difference at least on my machine. I verified it installed correctly, although I haven't played around with any of the settings apart from what is in the `benchmark_python.py` file
 * e3nn.c seems to be doing a little worse since the last time I compiled it... not sure whats going on there.

I think its good to have an array of benchmarks here, although I'll probably only include the best of each library in the main figure. Also might remove ipex if it doesn't seem to make a difference. Would be curious to see if you are getting any different results on your machine.

**Comment by mitkotak** [comment]
> A few notes:
> 
> * surprisingly, torch v2 (plotted underneath ipex, more plotting woes) seems to do marginally worse than plain torch, though we are measuring single-thread CPU performance so that could be a caveat.

Yup looks like that was the issue though the multithreaded performance than single threaded even for Torch and JAX which doesn't make sense


Screenshot 2024-06-27 at 1 30 26 AM

Screenshot 2024-06-27 at 12 39 26 AM


> * the addition of `ipex` seems to make no significant difference at least on my machine. I verified it installed correctly, although I haven't played around with any of the settings apart from what is in the `benchmark_python.py` file

Don't have an intel machine but my guess would be that it needs multithreading to do its magic.


> * e3nn.c seems to be doing a little worse since the last time I compiled it... not sure whats going on there; will need to investigate

Huh weird. How off it is ?

> 
> I think its good to have an array of benchmarks here, although I'll probably only include the best of each library in the main figure. Also might remove ipex if it doesn't seem to make a difference. Would be curious to see if you are getting any different results on your machine.
> 

Above results are from `AMD EPYC 7313 16-Core Processor`

We also should add a `batch` parameter to the C code since performance seems to be closing up at high L so wanna make sure its not just a overhead thing.

**Comment by teddykoker** [comment]
Getting comparable results on my CPU as well now:

benchmark

Regarding e3nn.c performance, I think I might have made a mistake with the benchmark previously -- for testing I had lowered the number of trials but I might not have run the benchmark_c.c codegen again when I increased it up to 100. Edited the makefile to ensure this is less likely to happen.

Regarding batching: how would that improve C performance without parallelization? I guess if parsing the irreps is time consuming it would be penalized for doing that but I'm not sure if that is the case...

**Comment by mitkotak** [comment]
> Regarding batching: how would that improve C performance without parallelization? I guess if parsing the irreps is time consuming it would be penalized for doing that but I'm not sure if that is the case...

Was just thinking from an overhead perspective and wanted to throw in some more work to do especially for lower Ls.

Also there's also this to keep in mind when reporting [numbers](https://github.com/mir-group/nequip/discussions/303#discussioncomment-5138754).

**Comment by mitkotak** [comment]
I think this PR is ready to merge we can continue the conversation on the next one that you file for Linear

**Pull request merged**
