### PR TITLE
Irreps Ops

### PR DESCRIPTION
**Pull request by teddykoker**
Functions:

  - [X]  `Irreps* irreps_tensor_product(Irreps* i1, Irreps* i2)`: creates irreps of the tensor product between two irreps
  - [x] `Irreps* irreps_concatenate(Irreps* i1, Irreps* i2)`: creates irreps of the concatenation of two irreps
  - [x] `Irreps* irreps_linear(Irreps* input, Irreps* output, bool force_irreps_out)`: creates irreps of the linear operation **removing unmatching irreps if `force_irreps_out==false`, but just copies `output` otherwise**
  - [x] `int linear_weight_size(Irreps* input, Irreps* output)`: computes the weight matrix size given input and output irreps

### CODE REVIEW

**Comment by teddykoker** [comment]
@mitkotak 

Benchmarking irreps from string vs computed tensor product:

```c
// tmp.c

#include <stdio.h>
#include <time.h>

#include "e3nn.h"

int main(void){
    Irreps* irreps1 = irreps_create("1x0e+1x1o+1x2e+1x3o+1x4e+1x5o+1x6e+1x7o");
    Irreps* irreps2 = irreps_create("128x0e+128x1o+128x2e+128x3o+128x4e+128x5o+128x6e+128x7o");

    const int trials = 1000;

    clock_t start = clock(); 
    for (int trial = 0; trial < trials; trial++) {
        Irreps* irrepso_gen = irreps_create("1024x0e+1792x1o+896x1e+2432x2e+1536x2o+2816x3o+2048x3e+3072x4e+2304x4o+3072x5o+2432x5e+2944x6e+2304x6o+2560x7o+2048x7e+2048x8e+1536x8o+1536x9o+1152x9e+1152x10e+768x10o+768x11o+512x11e+512x12e+256x12o+256x13o+128x13e+128x14e");
    }
    float elapsed = ((float) clock() - start) / CLOCKS_PER_SEC; 
    printf("from string, %f us\n", elapsed / trials * 1e6); 

    start = clock(); 
    for (int trial = 0; trial < trials; trial++) {
        Irreps* irrepso_computed = irreps_tensor_product(irreps1, irreps2);
    }
    elapsed = ((float) clock() - start) / CLOCKS_PER_SEC; 
    printf("computed, %f us\n", elapsed / trials * 1e6); 

    Irreps* irrepso_gen = irreps_create("1024x0e+1792x1o+896x1e+2432x2e+1536x2o+2816x3o+2048x3e+3072x4e+2304x4o+3072x5o+2432x5e+2944x6e+2304x6o+2560x7o+2048x7e+2048x8e+1536x8o+1536x9o+1152x9e+1152x10e+768x10o+768x11o+512x11e+512x12e+256x12o+256x13o+128x13e+128x14e");
    Irreps* irrepso_computed = irreps_tensor_product(irreps1, irreps2);
    irreps_print(irrepso_gen);
    irreps_print(irrepso_computed);

    irreps_free(irreps1);
    irreps_free(irreps2);
    irreps_free(irrepso_gen);
    irreps_free(irrepso_computed);
    return 0;
}
```

On my machine I am getting roughly:
```

```
from string, 4.241000 us
computed, 0.518000 us
```

So computing irreps speed is significantly faster than even reading from string.

**Comment by mitkotak** [comment]
Wow. Those vectorization super powers sure seem to be doing wonders. Can you stretch the string a bit more to see if there's a point at which it breaks even ?

**Comment by teddykoker** [comment]
With a tensor product of two lmax 50 tensors its still faster to compute than parsing the string. I'm sure trend reverses at some point since computation is $O(L^3)$ and parsing is $O(L)$, but I don't think its matters for any reasonable cases.

```c
// tmp.c

#include <stdio.h>
#include <time.h>

#include "e3nn.h"

int main(void){
    Irreps* irreps1 = irreps_create("1x0e+1x1o+1x2e+1x3o+1x4e+1x5o+1x6e+1x7o+1x8e+1x9o+1x10e+1x11o+1x12e+1x13o+1x14e+1x15o+1x16e+1x17o+1x18e+1x19o+1x20e+1x21o+1x22e+1x23o+1x24e+1x25o+1x26e+1x27o+1x28e+1x29o+1x30e+1x31o+1x32e+1x33o+1x34e+1x35o+1x36e+1x37o+1x38e+1x39o+1x40e+1x41o+1x42e+1x43o+1x44e+1x45o+1x46e+1x47o+1x48e+1x49o+1x50e");
    Irreps* irreps2 = irreps_create("128x0e+128x1o+128x2e+128x3o+128x4e+128x5o+128x6e+128x7o+128x8e+128x9o+128x10e+128x11o+128x12e+128x13o+128x14e+128x15o+128x16e+128x17o+128x18e+128x19o+128x20e+128x21o+128x22e+128x23o+128x24e+128x25o+128x26e+128x27o+128x28e+128x29o+128x30e+128x31o+128x32e+128x33o+128x34e+128x35o+128x36e+128x37o+128x38e+128x39o+128x40e+128x41o+128x42e+128x43o+128x44e+128x45o+128x46e+128x47o+128x48e+128x49o+128x50e");

    const int trials = 1000;

    clock_t start = clock(); 
    for (int trial = 0; trial < trials; trial++) {
        Irreps* irrepso_gen = irreps_create("6528x0e + 12800x1o + 6400x1e + 18944x2e + 12544x2o + 24832x3o + 18560x3e + 30592x4e + 24320x4o + 36096x5o + 29952x5e + 41472x6e + 35328x6o + 46592x7o + 40576x7e + 51584x8e + 45568x8o + 56320x9o + 50432x9e + 60928x10e + 55040x10o + 65280x11o + 59520x11e + 69504x12e + 63744x12o + 73472x13o + 67840x13e + 77312x14e + 71680x14o + 80896x15o + 75392x15e + 84352x16e + 78848x16o + 87552x17o + 82176x17e + 90624x18e + 85248x18o + 93440x19o + 88192x19e + 96128x20e + 90880x20o + 98560x21o + 93440x21e + 100864x22e + 95744x22o + 102912x23o + 97920x23e + 104832x24e + 99840x24o + 106496x25o + 101632x25e + 108032x26e + 103168x26o + 109312x27o + 104576x27e + 110464x28e + 105728x28o + 111360x29o + 106752x29e + 112128x30e + 107520x30o + 112640x31o + 108160x31e + 113024x32e + 108544x32o + 113152x33o + 108800x33e + 113152x34e + 108800x34o + 112896x35o + 108672x35e + 112512x36e + 108288x36o + 111872x37o + 107776x37e + 111104x38e + 107008x38o + 110080x39o + 106112x39e + 108928x40e + 104960x40o + 107520x41o + 103680x41e + 105984x42e + 102144x42o + 104192x43o + 100480x43e + 102272x44e + 98560x44o + 100096x45o + 96512x45e + 97792x46e + 94208x46o + 95232x47o + 91776x47e + 92544x48e + 89088x48o + 89600x49o + 86272x49e + 86528x50e + 83200x50o + 83200x51o + 80000x51e + 80000x52e + 76800x52o + 76800x53o + 73728x53e + 73728x54e + 70656x54o + 70656x55o + 67712x55e + 67712x56e + 64768x56o + 64768x57o + 61952x57e + 61952x58e + 59136x58o + 59136x59o + 56448x59e + 56448x60e + 53760x60o + 53760x61o + 51200x61e + 51200x62e + 48640x62o + 48640x63o + 46208x63e + 46208x64e + 43776x64o + 43776x65o + 41472x65e + 41472x66e + 39168x66o + 39168x67o + 36992x67e + 36992x68e + 34816x68o + 34816x69o + 32768x69e + 32768x70e + 30720x70o + 30720x71o + 28800x71e + 28800x72e + 26880x72o + 26880x73o + 25088x73e + 25088x74e + 23296x74o + 23296x75o + 21632x75e + 21632x76e + 19968x76o + 19968x77o + 18432x77e + 18432x78e + 16896x78o + 16896x79o + 15488x79e + 15488x80e + 14080x80o + 14080x81o + 12800x81e + 12800x82e + 11520x82o + 11520x83o + 10368x83e + 10368x84e + 9216x84o + 9216x85o + 8192x85e + 8192x86e + 7168x86o + 7168x87o + 6272x87e + 6272x88e + 5376x88o + 5376x89o + 4608x89e + 4608x90e + 3840x90o + 3840x91o + 3200x91e + 3200x92e + 2560x92o + 2560x93o + 2048x93e + 2048x94e + 1536x94o + 1536x95o + 1152x95e + 1152x96e + 768x96o + 768x97o + 512x97e + 512x98e + 256x98o + 256x99o + 128x99e + 128x100e");
    }
    float elapsed = ((float) clock() - start) / CLOCKS_PER_SEC; 
    printf("from string, %f us\n", elapsed / trials * 1e6); 

    start = clock(); 
    for (int trial = 0; trial < trials; trial++) {
        Irreps* irrepso_computed = irreps_tensor_product(irreps1, irreps2);
    }
    elapsed = ((float) clock() - start) / CLOCKS_PER_SEC; 
    printf("computed, %f us\n", elapsed / trials * 1e6); 
    irreps_free(irreps1);
    irreps_free(irreps2);
    return 0;
}
```

```
from string, 33.429998 us
computed, 18.279999 us
```

**Comment by teddykoker** [comment]
Also added a few helper functions `irreps_print`, `irreps_copy` and updated the tetris example to use these ops instead of hardcoding all the irreps manually.

**Pull request merged**
