### PR TITLE
Message computation example

### PR DESCRIPTION
**Pull request by mitkotak**
Thought a cute little example would be useful to show new-comers how the machinery can be used.

### CODE REVIEW

**Comment by teddykoker** [comment]
Nice! Maybe we can just replace the current example with this. I am currently working on implementing a simple tetris example as well (also implementing `concat` and a simple neighborlist function for this).

**Comment by teddykoker** [comment]
Also FYI I'm thinking about changing the API slightly to have functions use `Irreps` structs instead of the strings. I feel this is slightly more annoying UI as it requires calling `irreps_create()` and `irreps_free()`, but it should also make it easier to work with for things like computing irrep dimensions or tensor product output irreps. See the [`irreps`](https://github.com/teddykoker/e3nn.c/tree/irreps) branch.

**Comment by mitkotak** [comment]
Yup looks good. Since we are on the subject of syntax sugaring, would like to push for structs for weights as well with possibility of automatically handling conversion from weights list -> array and vice versa.

Small logistics things:

- Can you open up discussion section so that we can do RFCs ?
- Can you create WIP PRs whenever possible cause Github for some reason only pings me when there's a PR. 
Wanna stay completely synced on any action that might be happening :)

**Comment by mitkotak** [comment]
> Nice! Maybe we can just replace the current example with this. I am currently working on implementing a simple tetris example as well (also implementing `concat` and a simple neighborlist function for this).

Nice Tess would be proud ! Updated the README.md so ready for review and merge

**Comment by teddykoker** [comment]
> Yup looks good. Since we are on the subject of syntax sugaring, would like to push for structs for weights as well with possibility of automatically handling conversion from weights list -> array and vice versa.
> 

What are you thinking as an API for this? I thought about making structs with all the Paths, but that would make the code significantly more complicated, and I figured the current approach would work so long as all of the input/output irreps are always simplified, which is an easy enough assumption to maintain throughout the functions, as I've already ensured the tensor product simplifies its outputs. Figured I'd actually enforce the irreps always being sorted/simplified, which makes the `concat` operation simple as well.

> Small logistics things:
> 
>     * Can you open up discussion section so that we can do RFCs ?
>

Done

> 
>     * Can you create WIP PRs whenever possible cause Github for some reason only pings me when there's a PR.
>       Wanna stay completely synced on any action that might be happening :)
>

Will do!

**Comment by mitkotak** [comment]
> What are you thinking as an API for this? I thought about making structs with all the Paths, but that would make the code significantly more complicated, and I figured the current approach would work so long as all of the input/output irreps are always simplified, which is an easy enough assumption to maintain throughout the functions, as I've already ensured the tensor product simplifies its outputs. Figured I'd actually enforce the irreps always being sorted/simplified, which makes the `concat` operation simple as well.

Fair. I guess I was thinking more around the flexibility of being able to do `uuu`, `uvu` and mess around with who talks to whom but since we are shooting for Nequip here TP + Linear makes sense.

**Comment by mitkotak** [comment]
Also updated the code with the new API

**Pull request merged**
